### ISSUE TITLE
Complétion forcée, puis retour dans l'activité par l'étudiant

### ISSUE THREAD

**Issue by stephanebarcet** [sfraysse/moodle-trainingpath#1]
un apprenant n'a pas commencé ou pas terminé un contenu => statut incomplet
Un tuteur force la complétion => statut terminé + temps.
Si l'apprenant revient dans le contenu, le statut incomplet remonte.
Est-ce qu'on peut forcer le statut complété quelque soit  les futures actions de l'apprenant ?

**Comment by sfraysse** [comment]
C'est quoi comme contenu ?

En théorie, avec SCORM, c'est au contenu à récupérer le status précédent et à décider ce qu'il en fait, donc potentiellement éviter une régression.

Mais oui, on peut prévoir une option pour bloquer la régression. A intégrer dans SCORM Lite du coup, puis à propager vers AP et TP.

Je le marque en évolution.

**Comment by sfraysse** [comment]
Après vérification, il y a déjà une protection contre la régression de la complétion pour les contenus (et non pour les tests soumis à la notion de tentative).

J'ai essayé de reproduire le problème sans succès. Le contenu reste bien completed même si l'apprenant le relance et qu'il ne le finit pas.

Est-ce que tu aurais une procédure précise qui permette de reproduire le problème, si possible avec mon contenu de test ?

**Comment by stephanebarcet** [comment]
OK. Pb sur Moodle 3.4. Pas sur 3.5
