### ISSUE TITLE
Export xls - Mise en forme de l'en-tête

### ISSUE THREAD

**Issue by stephanebarcet** [sfraysse/moodle-trainingpath#10]
Actuellement, les en-tête de titre de tableaux dans les exports xls sont sur 6 colonnes, quelque soit la largeur du tableau.
Si le tableau fait 15 colonnes, est-il possible de centrer l'en-tête sur les 15 colonnes, au lieu de 6.
Ex : 
![image](https://user-images.githubusercontent.com/44055191/74040700-801ca500-49c4-11ea-8f0d-13de85d1d3a1.png)

**Comment by stephanebarcet** [comment]
Note que sur l'export par utilisateur, il faut réduire sur 5 colonnes (!)
![image](https://user-images.githubusercontent.com/44055191/74042874-9fb5cc80-49c8-11ea-89a9-3b0408076231.png)

**Comment by sfraysse** [comment]
ok
