### ISSUE TITLE
Renommer le bouton "export"

### ISSUE THREAD

**Issue by stephanebarcet** [sfraysse/moodle-trainingpath#11]
Sur un Learner progress (ex : 
https://onlineatpltraining.com/moodle/mod/trainingpath/report/learners.php?cmid=2191&group_id=46)
on a trois boutons d'export : 
1/ Export
2/ Export thèmes
3/ Export Users

Renommer le 1/ en Export global

**Comment by stephanebarcet** [comment]
Ou plutôt "Global export"

**Comment by sfraysse** [comment]
ok
