### ISSUE TITLE
Export XLS - Agrandissement d'une colonne

### ISSUE THREAD

**Issue by stephanebarcet** [sfraysse/moodle-trainingpath#12]
Dans l'export par utilisateur, la première colonne affiche le nom des séquences.
Actuellement, le nom est très long.
Est-il possible d'adapter automatiquement la largeur de cette colonne au texte contenu ?
Si non, demande de doubler au moins la largeur de la première colonne.

**Comment by sfraysse** [comment]
Adaptation automatique pas possible, mais ok pour doubler la largeur.
