### ISSUE TITLE
Moyenne de note - Pb d'arrondi

### ISSUE THREAD

**Issue by stephanebarcet** [sfraysse/moodle-trainingpath#13]
Les notes semblent être arrondis à la note inférieur 
Ex, pour l'initial, on devrait avoir 73+84+70+80=307
307/4=76.75, arrondi à 77%

Idem pour le remedial (84+84+91+80 / 4 = 84.75, arrondi à 85)
![image](https://user-images.githubusercontent.com/44055191/74043738-36cf5400-49ca-11ea-9196-763a2e4c5434.png)

**Comment by sfraysse** [comment]
ok
