### ISSUE TITLE
Renommage d'un bouton d'export

### ISSUE THREAD

**Issue by stephanebarcet** [sfraysse/moodle-trainingpath#14]
1/ Je visualise le rapport pour un thème (ex : https://onlineatpltraining.com/moodle/mod/trainingpath/report/certificate.php?cmid=2191&group_id=46&certificate_id=8333)
J'ai deux boutons "Export" et "Export seq"

2/ je vais sur le rapport global des learner progress (https://onlineatpltraining.com/moodle/mod/trainingpath/report/learners.php?cmid=2191&group_id=46&eval_only=0)
j'ai trois boutons "export", "export themes" et "export user".

Le bouton "export themes" du 2/ est identique au bouton "export" du 1/ (OK)

=> renommer le bouton "export" du 1/ en "export themes"

**Comment by sfraysse** [comment]
Euuu, pas sûr...

- Le bouton Export du 1/ est l'export du rapport en cours d'affichage, en l'occurrence celui du thème affiché à l'écran. C'est donc l'export d'un seul thème.

- L'export du 2/ est l'export de tous les thèmes du parcours, 1 thème par onglet. 

Ou bien j'ai mal compris la demande ?

**Comment by stephanebarcet** [comment]
OK. Je transmets. Je clos en attendant.
