### ISSUE TITLE
Export par sequence

### ISSUE THREAD

**Issue by stephanebarcet** [sfraysse/moodle-trainingpath#15]
J'ai 16 sequences. Le premier test apparaît dans la 4ème séquence.
Si j'affiche le rapport du thème avec toutes les séquences.
Je clique sur l'export Sequence, j'obtiens un fichier avec 16 onglets, avec toutes les infos de complétions. OK

Si je n'affiche que les séquences contenant des évaluations et que j'exporte, j'obtiens toujours 16 onglets, dont les 3 premiers sont vides.
[export.xlsx](https://github.com/sfraysse/moodle-trainingpath/files/4171784/export.xlsx)

**Comment by sfraysse** [comment]
Le fait qu'il y ait le 16 onglets dans les 2 cas ne me choque pas car c'est une option d'affichage du rapport, qui n'était pas supposée affecter l'export (tout du moins dans mon esprit).

- Question 1 : est-ce que tu souhaites que ça soit répercuté sur l'export ?

- Question 2 : est-ce que le fait que les 3 premiers onglets soient vides est anormal ou pas ? En d'autres termes, étaient-ils déjà vides lors de ton premier export avec toutes les séquences ?

**Comment by stephanebarcet** [comment]
Q1 : oui ; c'est ce qui se passe habituellement sur les autres exports
Lorsqu'on sélectionne seulement les séquences évaluées, le tableau n'affiche que les informations sur les séquences évaluées (les séquences sans évaluations sont invisibles).
Lorsqu'on sélectionne toutes les séquences, on voit toutes les séquences (dans mon exemples, les 16 onglets). 

Q2 : dans mon ex, les trois premiers onglets sont 
* renseignés si on affiche toutes les séquences (OK)
* vides si on n'affiches que les séquences évaluées (KO) => a supprimer

**Comment by sfraysse** [comment]
A noter que lorsque l'option **Show evaluated sequences only** est choisie, chaque rapport de séquence (donc chaque onglet Excel) n'affiche que les activités de type évaluation, et non les autres. C'est cohérent avec le fonctionnement des rapports Web.
C'est cohérent aussi pour toi ?
