### ISSUE TITLE
Export xls - Renommage en-tete de colonne

### ISSUE THREAD

**Issue by stephanebarcet** [sfraysse/moodle-trainingpath#17]
Pour une meilleure lecture, peut-on remplacer des en-têtes de colonnes dans les trois exports suivants : 
1/ dans le Learner progress, lorsqu'on est dans un thème, et qu'on exporte le thème
2/ dans le learner progress, au niveau du parcours complet et qu'on exporte tous les thèmes
3/ dans le Learner progress, au niveau du parcours complet, et qu'on exporte le global

- Remplacer le terme "Global" par "Average"
- Remplacer "Score" par "First tests"
- Remplacer "Remediation" par "Last tests"

Finalement, on peut résumer que la moyenne "score" correspond à la moyenne des premiers tests passé ; et "remédiation" correspond plus à la moyenne du dernier test passé par un élève (qu'il soit en remédiation ou pas)

**Comment by sfraysse** [comment]
OK pour 3/.

Pour 1/ et 2/, c'est un peu différent. L'export de chaque thème fait appaitre les séquences.
Pour chaque séquence, les 2 colonnes de score font apparaitre respectivement le score initial et remédial de la séquence (chaque séquence est supposée n'avoir qu'une évaluation initiale et qu'une finale).

Par mesure de sécurité, s'il y a plusieurs évals (initiale et/ou finale) dans la séquence, il s'agit de la dernière éval initiale et de la dernière éval finale.

Donc pour 1/ et 2/, je te propose de mettre "Initial" et "Remedial" et lieu de "First tests" et "Last tests".

Qu'en penses-tu ?

**Comment by sfraysse** [comment]
OK dans tous les cas pour "Global" > "Average", mais :
- Plutôt "Avg" pour ne pas étirer la cellule
- Valable aussi bien dans l'export que dans la version Web pour cohérence

Est-ce que ça te va ?

**Comment by sfraysse** [comment]
Pour 1/ et 2/, en fait c'est un peu plus compliqué :
- Toutes les colonnes sauf la dernière : Initial vs Remedial
- Dernière colonne (Avg) : First tests vs Last tests

Ca te semble cohérent ?

**Comment by stephanebarcet** [comment]
Oui pour 1 et 2
(le problème est de comprendre ce que veut dire la moyenne "Remedial", qui n'est pas la moyenne que des remedials)

(si tu as une autre proposition pour First test/Last test, je suis intéressé)

**Comment by sfraysse** [comment]
Pour "Global" > "Average", en fait c'est peut-être une fausse bonne idée.
Ca marche sur les rapports simples (qu'avec les scores), mais pas pour les rapports complets qui disposent en plus des colonnes "Progress" et "Time". Hors il s'agit de la progression et du temps global, pas de la moyenne des progression et temps passé.
Donc perso, je laisserais "Global" sur tous les rapports. 
Qu'en penses-tu ?

**Comment by stephanebarcet** [comment]
Bien vu. Je vois avec l'équipe.

**Comment by stephanebarcet** [comment]
Finalement, on suit ta remarque sur un maintien de "Global" partout sur 1/, 2/ et 3/ (et on oublie Average).
Pour 3/, plutôt que "1st test" et" last test", afficher "INIT-AVG" et "FINAL-AVG" (ca semble plus parlant)
Pour 1/ et 2/, on reste sur "Init" et Remedial" pour l'affichage des séquences, puis sur "INIT-AVG" et "FINAL-AVG" lorsqu'on fait la moyenne à droite du tableau.

**Comment by stephanebarcet** [comment]
ok
