### ISSUE TITLE
Export XLS - Message d'erreur

### ISSUE THREAD

**Issue by stephanebarcet** [sfraysse/moodle-trainingpath#18]
Dans un report global, si je clique sur l'export des thèmes (simple ou full), je dois attendre quelques secondes, et je vois afficher ce message (en mode développeur)

Notice: Trying to get property 'header' of non-object in /var/www/html/moodle/mod/trainingpath/report/certificate.php on line 131

Notice: Trying to get property 'cells' of non-object in /var/www/html/moodle/mod/trainingpath/report/certificate.php on line 131

Warning: count(): Parameter must be an array or an object that implements Countable in /var/www/html/moodle/mod/trainingpath/report/certificate.php on line 131

Fatal error: Maximum execution time of 30 seconds exceeded in /var/www/html/moodle/lib/phpexcel/PHPExcel/Cell.php on line 896

Note que je n'ai pas ca sur tous les autres exports XLS. C'est plutôt rapide. Ca semble être un problème de time out ?

**Comment by sfraysse** [comment]
Bon, pour commencer, on peut tester avec cette nouvelle version qui corrige un potentiel problème si un thème est vide ou n'a aucune donnée utilisateur :
https://github.com/sfraysse/moodle-trainingpath/releases/tag/v3.5.4

Je ne suis pas sûr de mon coup car ce qui m’interpelle c'est le message d'erreur sur le max execution time. Mais essayons déjà ça...

**Comment by stephanebarcet** [comment]
Le problème ne se produit plus. Je clos donc. Merci.
