### ISSUE TITLE
Pb sur temps pris en compte sur une complétion

### ISSUE THREAD

**Issue by stephanebarcet** [sfraysse/moodle-trainingpath#2]
Sur un training path très complexe, lorsque je complète un contenu, le temps remonté est le temps minimum.
J'ai importé ce training path dans un autre cours. Je constate le même comportement.
J'ai dupliqué ce dernier traning path et j'ai retiré beaucoup de séquence pour le simplifier au maximum.
Je fais un planning puis je complète le même contenu. Le temps remonté est le temps "scenarisé"-moyen.

**Comment by sfraysse** [comment]
Mmmmm, difficile à reproduire. Ca serait possible d'accéder au parcours qui pose problème ?

**Comment by stephanebarcet** [comment]
https://onlineatpltraining.com/moodle/course/view.php?id=6
Tu dois avoir recu ID et MdP

**Comment by stephanebarcet** [comment]
Le premier TP est OK (super simple avec ton content SCORM de test 

Le deuxième est le complexe avec toutes les séquences basée sur Scenari
J'obtiens https://onlineatpltraining.com/moodle/mod/trainingpath/report/sequence.php?cmid=2180&group_id=46&sequence_id=7706&eval_only=0
avec 45 minutes qui est le temps minimum.

Le troisième TP avec le même contenu (j'ai juste changé le temps, j'affiche 8 minutes pour un temps mini de 5 minutes)
https://onlineatpltraining.com/moodle/mod/trainingpath/report/sequence.php?cmid=2181&group_id=46&sequence_id=7996&eval_only=0

**Comment by sfraysse** [comment]
<img width="692" alt="Capture" src="https://user-images.githubusercontent.com/14231525/72440475-32d45b80-37a9-11ea-84e7-575530a0e258.PNG">

**Comment by sfraysse** [comment]
De mon coté, le temps remonte correctement, avant et après complétion.

N'avais-tu pas réglé le maximum time factor sur 1 lors de tes tests ?
<img width="315" alt="Capture" src="https://user-images.githubusercontent.com/14231525/72441984-f7875c00-37ab-11ea-88fb-a902a4f980a5.PNG">

**Comment by stephanebarcet** [comment]
Clos. Lorsqu'on ré-enregistre le thème, on retrouve le fonctionnement correct (on force avec le temps calculé).
