### ISSUE TITLE
Affichage d'un temps et complétion

### ISSUE THREAD

**Issue by stephanebarcet** [sfraysse/moodle-trainingpath#3]
Un contenu est vu par un apprenant, non complet, pendant 5 minutes alors que le temps mini est de 15 minutes.
On force la complétion=> l'affichage est "complet - 5 minutes", de couleur verte.
=> KO.
Par contre, si l'apprenant retourne dans la page de présentation de contenu (celle qui affiche le bouton Start"), alors le temps se modifie.
Est-ce qu'on peut forcer ce temps sans que l'élève retourne sur la page de présentation ?

**Comment by sfraysse** [comment]
ok

**Comment by sfraysse** [comment]
En relisant mon code, je réalise que ce fonctionnement était volontaire. Mon raisonnement était sans doute de dire, on force la complétion, mais on respecte le temps passé par l'élève s'il y en a un (ici 5min). Si ce raisonnement est correct, bien sûr, lorsque l'utilisateur retourne sur sa page, la valeur ne devrait pas changer et rester à 5min, donc il y a bien un bug.

Mais du coup je m'interroge sur le fonctionnement que l'on veut vraiment et je vois 3 possibilités :

1. **On ne touche pas au temps de l'élève s'il y en a un** (comme aujourd'hui, et on rectifie pas lorsque l'élève va sur sa page).

2. **On force systématiquement la complétion ET le temps**, même si l'élève a déjà passé du temps (le temps élève sera donc écrasé).

3. **On ne force le temps QUE SI le temps passé par l'élève est insuffisant**, donc inférieur au temps forcé (histoire de le mettre à niveau). En revanche, s'il avait passé un temps supérieur au temps forcé, alors on respecte le temps passé par l'élève. 

Personnellement, j'opterais plutôt pour l'option 3. 

Qu'en penses-tu ?

**Comment by sfraysse** [comment]
Note pour moi : report/lib lignes 175 et 202 ($forced_time)

**Comment by sfraysse** [comment]
Oublie ma question. Elle se résout avec le point #4 (fixer le temps lorsque l'on force la complétion).
S'il y a un temps élève, il est affiché par défaut comme temps à prendre en compte lorsque l'on force la complétion (ce qui revient à respecter le temps passé).
Mais l'utilisateur est libre d'augmenter ce temps, donc tout va bien.
