### ISSUE TITLE
Evol - forcer la complétion avec un temps spécifique

### ISSUE THREAD

**Issue by stephanebarcet** [sfraysse/moodle-trainingpath#4]
Lorsqu'on force la complétion, est-il possible de spécifier le temps pris en compte (autre chose que le temps "scenarisé" par défaut actuellement).
Par ex, le temps mini est 10 minutes, le temps "scenarisé" est de 15 minutes. On pourrait compléter avec un temps de 13 minutes (aujourd'hui par défaut, c'est 15 minutes).

**Comment by sfraysse** [comment]
Oui, je marque en évolution.

**Comment by stephanebarcet** [comment]
Comme le tuteur devra indiquer une valeur, il faudrait afficher le temps "scenarisé" (valeur par défaut ?).

**Comment by stephanebarcet** [comment]
Je note un petit effet de bord. Un tuteur peut forcer la complétion avec un temps inférieur au temps minimum. Dans ce cas, on devrait avoir un cadre rouge sur le temps, or il est vert.
Au tuteur de faire attention lorsqu'il donne un temps.
