### ISSUE TITLE
Rajout d'un paramètre pour les test de remédiation

### ISSUE THREAD

**Issue by stephanebarcet** [sfraysse/moodle-trainingpath#5]
Tu as rajouté il y a quelques temps maintenant le paramètre trainingpath | prefered_activity_access_eval pour choisir par défaut comment se comporte un test (ouvert/fermé).
Mais cela ne marche pour que les tests initiaux.
Pour les remedial, on est toujours sur de l'auto-ouverture).
Je te propose de créer un paramètre pour ces tests de remédiation, si pas trop compliqué.

**Comment by sfraysse** [comment]
ok

**Comment by sfraysse** [comment]
Nécessite un paramètre de plugin séparé (prefered_activity_access_eval_remedial) car les options possibles ne sont pas les mêmes (ex. auto-completion).
