### ISSUE TITLE
Exports Excel simplifiés (sans temps ni progression)

### ISSUE THREAD

**Issue by stephanebarcet** [sfraysse/moodle-trainingpath#6]
Sur l'export du parcours complet, on a un onglet avec une ligne par élève, et des colonnes par thèmes, puis, pour chaque thème, 3 colonnes (progression, temps, score).
Les utilisateurs voudraient le même tableau mais qui n'afficherait que le temps (suppression de la progression et du temps).
Du coup, est-il possible d'ajouter un onglet avec ce tableau simplifié ?

**Comment by sfraysse** [comment]
ok

**Comment by stephanebarcet** [comment]
Je corrige : on ne conserve que les score (on supprime le temps et la progression).

**Comment by sfraysse** [comment]
OK. 
Ne concerne que l'export global, et non [Export Themes] ni [Export Users] ?

**Comment by stephanebarcet** [comment]
OK pour l'export global (ajout d'un nouvel onglet simplifié).
Pas de changement pour l'export par User.
Pour l'export par certif :
* dans l'export actuel, les notes de remédiation sont manquantes => à corriger
* ajouter un bouton pour l'export par thème simplifié: on ne trouve que les notes (initial + remedial).

**Comment by sfraysse** [comment]
ok

**Comment by stephanebarcet** [comment]
>     * dans l'export actuel, les notes de remédiation sont manquantes => à corriger

En fait c'est valable pour tous les exports XLS

**Comment by sfraysse** [comment]
ok

**Comment by sfraysse** [comment]
Du coup, pour les rapports simplifiés qui n'exportent que le score, on n'exporte que le score initial ou bien initial et remédial ?

**Comment by stephanebarcet** [comment]
Sur tous les rapport Thèmes (simplifié ou complet), on a besoin de l'initial et des notes après remedial

**Comment by sfraysse** [comment]
Affichage des scores remédial dans un autre ticket : #16

**Comment by sfraysse** [comment]
**Dans la page d'export principale**, afin d'avoir un résultat cohérent et simple à comprendre, on dispose désormais de 2 rangées de boutons d'export : export simple et export complet. Du coup, je n'ai pas repris l'idée d'un export général avec 2 onglets qui rendait les choses plus confuses (et plus complexes coté implémentation).

![Capture](https://user-images.githubusercontent.com/14231525/74858650-f9fa4a00-5345-11ea-9213-fe581a2210ba.JPG)

A noter un point important : les exports simples focalisent sur les notes, donc les séquences non évaluées ne sont pas exportées. Les exports complets exportent toujours toute les séquences.

**Comment by sfraysse** [comment]
**Sur les autres pages d'export**, je n'ai gardé qu'une rangée de boutons. Mais on dispose aussi de l'option **Show evaluated sequences only** dont on a déjà vu qu'elle avait une influence sur les exports.

- **Lorsque Show evaluated sequences only est activé**, il s'agit en fait d'un export simple, avec les scores des séquences évaluées uniquement.

 - **Lorsque Show evaluated sequences only n'est pas activé**, il s'agit en fait d'un export complet, avec temps, progress et scores de toutes les séquences.

Le tout me semble assez cohérent, mais je te laisse bien sûr valider.

![Capture](https://user-images.githubusercontent.com/14231525/74860446-ee5c5280-5348-11ea-906e-f1fdd89e50e1.JPG)

**Comment by stephanebarcet** [comment]
Petit détail :
1/ dans les exports des séquences pour un thème donné, (rapport des séances évaluées uniquement) : on a la première colonne qui est dupliquée
2/ idem dans l'export d'une séquence donnée (évaluation uniquement)

![image](https://user-images.githubusercontent.com/44055191/75251387-ca7e8e00-57da-11ea-8441-7c015b8655ba.png)

**Comment by stephanebarcet** [comment]
ok
